package fr.info.orleans.ws.controleur;

public enum Ordres {ERREUR_INSCRIPTION_INCOMPLETE,ERREUR_INSCRIPTION_EXISTANT,ERREUR_CONNEXION,SHOW_MENU, INSCRIPTION_OK, ERREUR_FORMAT_DATE, ERREUR_NB_KILOS, ERREUR_MAJ, RECHARGE_CREATION_OK, RECHARGE_MAJ_OK, DATA_UPDATED, SHOW_GESTION
}
