

###

POST http://localhost:8080/api/cafews/compte
Content-type: application/json

{
 "nom": "Luck",
 "prenom": "Luk",
 "email": "luck.luke@farwest.net"
}
###


###

POST http://localhost:8080/api/cafews/recharge?nbKilos=12
Content-type: application/json
cleSecrete:57efa445-ae16-46e0-a20a-810d30b93138

###

GET http://localhost:8080/api/cafews/recharge/2f12cd67-5602-4b26-a362-c06a2fe77438
Content-type: application/json
cleSecrete:57efa445-ae16-46e0-a20a-810d30b93138


###

GET http://localhost:8080/api/cafews/recharge
Content-type: application/json
cleSecrete:57efa445-ae16-46e0-a20a-810d30b93138

###

PATCH http://localhost:8080/api/cafews/recharge/2f12cd67-5602-4b26-a362-c06a2fe77438
cleSecrete:57efa445-ae16-46e0-a20a-810d30b93138
Content-type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<RechargeCafeDTO>
    <id>2f12cd67-5602-4b26-a362-c06a2fe77438</id>
	<dateRecharge>04-04-2024</dateRecharge>
</RechargeCafeDTO>

###

GET http://localhost:8080/api/cafews/recharge?dateDebut=01-12-2023
Content-Type: application/json
cleSecrete:57efa445-ae16-46e0-a20a-810d30b93138

###