spring:
  application:
    name: forum
security:
  jwt:
    issuer: forum-jwt-authentification
    expiration-minutes: 15
    key:
      public: classpath:rsaKey.public
      private: classpath:rsaKey.private
